#name, main, version and api are required
name: PowerBlockz
main: PowerBlockz\main
version: 1.1.0
api: 3.0.0

author: M4nt0s
description: Walk over a block for special powers.
website: Cooming soon....
commands:
 example:
  description: Example command
  usage: "Usage: /example"
  permission: exampleplugin.command.example
permissions:
 exampleplugin.command.example:
  description: "Allows the user to run the example command"
  default: true