#name, main, version and api are required
name: PowerBlockz
main: PowerBlockz\main
version: 1.1.0
api: 3.0.0

author: M4nt0s
description: Walk over a block for special powers.
website: Cooming soon....
